---
# Source: mongogui/templates/all_in_one.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongogui-secret
type: Opaque
data:
  mongo.url:
---
# Source: mongogui/templates/all_in_one.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongogui-service
spec:
  type: ClusterIP
  ports:
    - port: 4321
      targetPort: 4321
  selector:
    app: mongogui
---
# Source: mongogui/templates/all_in_one.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongogui
  labels:
    app: mongogui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongogui
  template:
    metadata:
      labels:
        app: mongogui
    spec:
      containers:
        - name: mongogui
          image: alexanderczigler/mongo-gui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4321
              protocol: TCP
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: mongourl
                  name: mongogui-secret
