---
apiVersion: v1
kind: Service
metadata:
  name: mongogui-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: tcp
  selector:
    app: mongogui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongogui
  labels:
    app: mongogui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongogui
  template:
    metadata:
      labels:
        app: mongogui
    spec:
      containers:
        - name: mongogui
          # image: alexanderczigler/mongo-gui:latest
          # image: mongoclient/mongoclient:4.0.1
          image: haohanyang/compass-web:0.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp
              # containerPort: 4321
              # containerPort: 3000
              containerPort: 8080
              protocol: TCP
          # env:
          #   - name: MONGO_URL
          #     valueFrom:
          #       secretKeyRef:
          #         key: mongo.url
          #         name: mongogui-secret
