---
apiVersion: v1
kind: Service
metadata:
  name: allure-docker-service
  labels:
    app: allure-docker-service
spec:
  type: ClusterIP
  selector:
    app: allure-docker-service
  ports:
    - name: http-port
      protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: allure-docker-service
  labels:
    app: allure-docker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allure-docker-service
  template:
    metadata:
      labels:
        app: allure-docker-service
    spec:
      containers:
        - name: allure-docker-service
          image: frankescobar/allure-docker-service:2.27.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-port
              protocol: TCP
              containerPort: 5050
          env:
            - name: "CHECK_RESULTS_EVERY_SECONDS"
              value: "NONE"
            - name: "KEEP_HISTORY"
              value: "1"
            - name: "KEEP_HISTORY_LATEST"
              value: "25"
