{{- if and (.Values.volume.enabled) (not .Values.volume.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "allure.fullname" . }}-data
  labels:
    {{- include "allure-api.selectorLabels" . | nindent 4 }}
{{- if .Values.volume.annotations }}
  annotations:
{{ toYaml .Values.volume.annotations | indent 4 }}
{{- end }}
spec:
{{- with .Values.volume }}
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  volumeMode: Filesystem
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}
