---
nameOverride: ""
fullnameOverride: ""

imagePullSecrets: {}
deploymentAnnotations: {}

api:
  replicaCount: 1
  image:
    registry: docker.io
    repository: lovemew67/allure-docker-service
    tag: "2.27.0"
    digest: ~
    pullPolicy: Always
  podAnnotations: {}
  podSecurityContext:
    fsGroup: 1000
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  resources: {}
  service:
    type: ClusterIP
    port: 80
  nodeSelector: {}
  tolerations: []
  devMode: false

ui:
  replicaCount: 1
  image:
    registry: docker.io
    repository: lovemew67/allure-docker-service-ui
    tag: "7.0.3"
    digest: ~
    pullPolicy: Always
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  service:
    type: ClusterIP
    port: 80
  nodeSelector: {}
  tolerations: []

keepHistory: true
keepHistoryLatest: 25
updateFrequency: NONE
securityEnabled: false
publicViewerEndpoint: false
apiCredentials:
  SECURITY_USER: "admin"
  SECURITY_PASS: "admin_pass"
  SECURITY_VIEWER_USER: "viewer"
  SECURITY_VIEWER_PASS: "viewer_pass"
credentials: api-credentials

volume:
  enabled: true
  existingClaim: ""
  storageClassName: ""
  size: 5Gi
  accessModes:
    - ReadWriteOnce

ingress:
  tls: true
  hostname: ""
